### ISSUE TITLE
Potential helper script cross-platform issues

### ISSUE THREAD

**Issue by int00h5525** [dirtbags/moth#103] opened 2019-11-18 21:52 UTC

**Comment by int00h5525** [comment] 2019-11-25 19:28
helper.js may not work correctly on some otherwise-supported browsers?

**Comment by nealey** [comment] 2021-03-12 00:14
It had a problem in Firefox that I fixed in https://github.com/dirtbags/moth/commit/30754fa8e9f877cc4f1bf235f78aa308d88bb1dc.

If we find another problem, let's document the browser that's having the problem, and what the problem is :)

**Closed by nealey** 2021-03-12 00:14 UTC
Labels: bug, frontend
